#!/usr/bin/env python3
"""
Generate Per-Residue Fragment Pair Grid

Creates a grid visualization with one subplot per protein position,
showing all unique fragment pairs that measure each position, colored by q-value.

This script can be used standalone, but note that the fragment pair grid
is also automatically generated when running generate_combined_plot.py
(using the same q-values and data for consistency).
"""

import argparse
import sys
import os

# Add current directory to path to import the module
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from combined_overhang_visualization import (
    create_combined_visualization,
    parse_fasta
)


def main():
    parser = argparse.ArgumentParser(
        description='Generate per-residue fragment pair grid visualization. '
                    'Note: This is automatically generated by generate_combined_plot.py. '
                    'This standalone script regenerates it using the same logic and q-values.'
    )
    parser.add_argument('--csv', required=True, help='Comet CSV output file')
    parser.add_argument('--fasta', required=True, help='FASTA file with protein sequences')
    parser.add_argument('--output', default='fragment_pair_grid.png',
                       help='Output PNG file (default: fragment_pair_grid.png)')
    parser.add_argument('--protein', help='Specific protein ID to visualize (optional)')
    parser.add_argument('--c-ions-only', action='store_true',
                       help='Filter to show only c ion fragment pairs')
    parser.add_argument('--z-ions-only', action='store_true',
                       help='Filter to show only z/z+1 ion fragment pairs')
    parser.add_argument('--no-filtering', action='store_true',
                       help='Skip all filtering and include all peptides with overhangs')
    
    args = parser.parse_args()
    
    # Validate ion type flags (mutually exclusive)
    if args.c_ions_only and args.z_ions_only:
        print("Error: --c-ions-only and --z-ions-only are mutually exclusive")
        return
    
    # Determine ion type filter
    ion_type_filter = None
    if args.c_ions_only:
        ion_type_filter = 'c'
    elif args.z_ions_only:
        ion_type_filter = 'z'
    
    # Get protein ID
    sequences = parse_fasta(args.fasta)
    if not sequences:
        print("Error: No sequences found in FASTA file")
        return
    
    if args.protein:
        protein_id = args.protein
    else:
        protein_id = list(sequences.keys())[0]
        print(f"No protein specified, using first protein: {protein_id}")
    
    # Note: The fragment pair grid is generated automatically by create_combined_visualization
    # We'll create a temporary combined plot to extract the data, then generate just the grid
    # This ensures we use the exact same q-values and filtering logic
    import tempfile
    temp_output = tempfile.mktemp(suffix='.png', prefix='temp_combined_')
    
    print("Generating fragment pair grid using same logic as combined plot...")
    print("(This will also generate a temporary combined plot to extract data)")
    
    # Generate combined plot (which automatically generates the fragment pair grid)
    # The fragment pair grid will be saved as {output}_fragment_pair_grid.png
    create_combined_visualization(args.csv, protein_id, args.fasta, temp_output, 
                                 ion_type_filter=ion_type_filter, no_filtering=args.no_filtering,
                                 use_two_pass=False, no_progressive=True, no_two_pass=True)
    
    # Move the fragment pair grid to the desired output location
    fragment_grid_output = temp_output.replace('.png', '_fragment_pair_grid.png')
    if os.path.exists(fragment_grid_output):
        import shutil
        shutil.move(fragment_grid_output, args.output)
        print(f"Fragment pair grid saved to: {args.output}")
        
        # Clean up temporary file
        if os.path.exists(temp_output):
            os.remove(temp_output)
    else:
        print(f"Warning: Fragment pair grid not found at {fragment_grid_output}")


if __name__ == '__main__':
    main()
